development:
  adapter:  postgresql
  encoding: utf8
  database:  ticket_development
  pool:     5
  username: postgres
  password: pp1994


test:
  adapter:  postgresql
  encoding: utf8
  database:  ticket_test
  pool:     5
  username: postgres
  password: pp1994